### ISSUE TITLE
hashPassword hiányzik a UserManager.js-ből

### ISSUE THREAD

**Issue by jimmyja** [attrecto/Attrecto-Academy-JS-Backend#1]
A login branch manager/UserManager.js 25 sorából hiányzik ez a sor:
userObject.password = await util.hashPassword(userObject.password);

3. órán ezt a sort hozzáadtuk a fájlhoz, de a giten lévő fájlban nincs benne.

**Comment by GerSzabi** [comment]
Köszi az infót. A tag-eléseknél elkeveredett valami. A login branchen már fixed.
(git checkout login)
